# Generated by Django 3.2.7 on 2021-09-25 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_apartamento', models.IntegerField(blank=True, verbose_name='Número do apartamento')),
                ('nome_proprietario', models.CharField(max_length=200)),
                ('cpf_proprietario', models.CharField(max_length=14, unique=True)),
                ('bloco', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fone_morador', models.TextField(max_length=100)),
                ('email_morador', models.EmailField(max_length=100)),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('email_proprietario', models.EmailField(default='', max_length=200, verbose_name='Email')),
                ('fone_proprietario', models.IntegerField(blank=True, verbose_name='Número de telefone')),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ultima_edicao', models.DateTimeField(auto_now=True)),
                ('apartamento_publicado', models.BooleanField(default=False)),
            ],
        ),
    ]
